# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Base.proto',
  package='PBData',
  serialized_pb=_b('\n\nBase.proto\x12\x06PBData\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x02(\t\"\x15\n\x04\x42ool\x12\r\n\x05value\x18\x01 \x02(\x08\"\x14\n\x03Int\x12\r\n\x05value\x18\x01 \x02(\x03\"\x15\n\x04UInt\x12\r\n\x05value\x18\x01 \x02(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STRING = _descriptor.Descriptor(
  name='String',
  full_name='PBData.String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PBData.String.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='PBData.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PBData.Bool.value', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=68,
)


_INT = _descriptor.Descriptor(
  name='Int',
  full_name='PBData.Int',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PBData.Int.value', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=90,
)


_UINT = _descriptor.Descriptor(
  name='UInt',
  full_name='PBData.UInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PBData.UInt.value', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['Int'] = _INT
DESCRIPTOR.message_types_by_name['UInt'] = _UINT

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), dict(
  DESCRIPTOR = _STRING,
  __module__ = 'Base_pb2'
  # @@protoc_insertion_point(class_scope:PBData.String)
  ))
_sym_db.RegisterMessage(String)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), dict(
  DESCRIPTOR = _BOOL,
  __module__ = 'Base_pb2'
  # @@protoc_insertion_point(class_scope:PBData.Bool)
  ))
_sym_db.RegisterMessage(Bool)

Int = _reflection.GeneratedProtocolMessageType('Int', (_message.Message,), dict(
  DESCRIPTOR = _INT,
  __module__ = 'Base_pb2'
  # @@protoc_insertion_point(class_scope:PBData.Int)
  ))
_sym_db.RegisterMessage(Int)

UInt = _reflection.GeneratedProtocolMessageType('UInt', (_message.Message,), dict(
  DESCRIPTOR = _UINT,
  __module__ = 'Base_pb2'
  # @@protoc_insertion_point(class_scope:PBData.UInt)
  ))
_sym_db.RegisterMessage(UInt)


# @@protoc_insertion_point(module_scope)
