# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bt_message_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bt_message_protocol.proto',
  package='BTMessageProtocol',
  serialized_pb=_b('\n\x19\x62t_message_protocol.proto\x12\x11\x42TMessageProtocol\"q\n\x0bGameMessage\x12\x0e\n\x06msg_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\x03\x12\x10\n\x08meta_tag\x18\x03 \x01(\t\x12\x0f\n\x07\x66rom_id\x18\x04 \x01(\x05\x12\x0e\n\x06to_ids\x18\x05 \x03(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\x0c\"4\n\x0eGameMessageAck\x12\x0e\n\x06msg_id\x18\x01 \x01(\x03\x12\x12\n\nerror_code\x18\x02 \x01(\x05*\x1f\n\x07\x43ommand\x12\x14\n\x10\x43MD_GAME_MESSAGE\x10\x01*\x1e\n\tErrorCode\x12\x11\n\rERROR_SUCCESS\x10\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='BTMessageProtocol.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_GAME_MESSAGE', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=217,
  serialized_end=248,
)
_sym_db.RegisterEnumDescriptor(_COMMAND)

Command = enum_type_wrapper.EnumTypeWrapper(_COMMAND)
_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='BTMessageProtocol.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_SUCCESS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=250,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
CMD_GAME_MESSAGE = 1
ERROR_SUCCESS = 0



_GAMEMESSAGE = _descriptor.Descriptor(
  name='GameMessage',
  full_name='BTMessageProtocol.GameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='BTMessageProtocol.GameMessage.msg_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='BTMessageProtocol.GameMessage.app_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta_tag', full_name='BTMessageProtocol.GameMessage.meta_tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_id', full_name='BTMessageProtocol.GameMessage.from_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_ids', full_name='BTMessageProtocol.GameMessage.to_ids', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='BTMessageProtocol.GameMessage.content', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=161,
)


_GAMEMESSAGEACK = _descriptor.Descriptor(
  name='GameMessageAck',
  full_name='BTMessageProtocol.GameMessageAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='BTMessageProtocol.GameMessageAck.msg_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='BTMessageProtocol.GameMessageAck.error_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=215,
)

DESCRIPTOR.message_types_by_name['GameMessage'] = _GAMEMESSAGE
DESCRIPTOR.message_types_by_name['GameMessageAck'] = _GAMEMESSAGEACK
DESCRIPTOR.enum_types_by_name['Command'] = _COMMAND
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE

GameMessage = _reflection.GeneratedProtocolMessageType('GameMessage', (_message.Message,), dict(
  DESCRIPTOR = _GAMEMESSAGE,
  __module__ = 'bt_message_protocol_pb2'
  # @@protoc_insertion_point(class_scope:BTMessageProtocol.GameMessage)
  ))
_sym_db.RegisterMessage(GameMessage)

GameMessageAck = _reflection.GeneratedProtocolMessageType('GameMessageAck', (_message.Message,), dict(
  DESCRIPTOR = _GAMEMESSAGEACK,
  __module__ = 'bt_message_protocol_pb2'
  # @@protoc_insertion_point(class_scope:BTMessageProtocol.GameMessageAck)
  ))
_sym_db.RegisterMessage(GameMessageAck)


# @@protoc_insertion_point(module_scope)
