# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FBAccount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FBAccount.proto',
  package='PBData',
  serialized_pb=_b('\n\x0f\x46\x42\x41\x63\x63ount.proto\x12\x06PBData\"I\n\tFbConnect\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03uid\x18\x02 \x01(\x04\x12\x0e\n\x06\x66\x62_uid\x18\x03 \x01(\x04\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\r\"\xdc\x01\n\x06\x46\x62User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\tfb_app_id\x18\x02 \x01(\x04\x12\x0e\n\x06\x66\x62_uid\x18\x03 \x01(\x04\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x0e\n\x06gender\x18\x07 \x01(\r\x12\x19\n\x11token_expiry_time\x18\x08 \x01(\r\x12\x13\n\x0b\x63reate_time\x18\t \x01(\r\x12\x13\n\x0bupdate_time\x18\n \x01(\r\x12\x1b\n\x13\x66riends_update_time\x18\x0b \x01(\r\"g\n\rFbUserMapping\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x66\x62_uid\x18\x02 \x01(\x04\x12\x11\n\tfb_app_id\x18\x03 \x01(\x04\x12\x12\n\nfb_app_uid\x18\x04 \x01(\x04\x12\x13\n\x0b\x63reate_time\x18\x05 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FBCONNECT = _descriptor.Descriptor(
  name='FbConnect',
  full_name='PBData.FbConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.FbConnect.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='PBData.FbConnect.uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_uid', full_name='PBData.FbConnect.fb_uid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='PBData.FbConnect.create_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=100,
)


_FBUSER = _descriptor.Descriptor(
  name='FbUser',
  full_name='PBData.FbUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.FbUser.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_app_id', full_name='PBData.FbUser.fb_app_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_uid', full_name='PBData.FbUser.fb_uid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='PBData.FbUser.access_token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='PBData.FbUser.email', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='PBData.FbUser.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='PBData.FbUser.gender', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token_expiry_time', full_name='PBData.FbUser.token_expiry_time', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='PBData.FbUser.create_time', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='PBData.FbUser.update_time', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friends_update_time', full_name='PBData.FbUser.friends_update_time', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=323,
)


_FBUSERMAPPING = _descriptor.Descriptor(
  name='FbUserMapping',
  full_name='PBData.FbUserMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.FbUserMapping.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_uid', full_name='PBData.FbUserMapping.fb_uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_app_id', full_name='PBData.FbUserMapping.fb_app_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_app_uid', full_name='PBData.FbUserMapping.fb_app_uid', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='PBData.FbUserMapping.create_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['FbConnect'] = _FBCONNECT
DESCRIPTOR.message_types_by_name['FbUser'] = _FBUSER
DESCRIPTOR.message_types_by_name['FbUserMapping'] = _FBUSERMAPPING

FbConnect = _reflection.GeneratedProtocolMessageType('FbConnect', (_message.Message,), dict(
  DESCRIPTOR = _FBCONNECT,
  __module__ = 'FBAccount_pb2'
  # @@protoc_insertion_point(class_scope:PBData.FbConnect)
  ))
_sym_db.RegisterMessage(FbConnect)

FbUser = _reflection.GeneratedProtocolMessageType('FbUser', (_message.Message,), dict(
  DESCRIPTOR = _FBUSER,
  __module__ = 'FBAccount_pb2'
  # @@protoc_insertion_point(class_scope:PBData.FbUser)
  ))
_sym_db.RegisterMessage(FbUser)

FbUserMapping = _reflection.GeneratedProtocolMessageType('FbUserMapping', (_message.Message,), dict(
  DESCRIPTOR = _FBUSERMAPPING,
  __module__ = 'FBAccount_pb2'
  # @@protoc_insertion_point(class_scope:PBData.FbUserMapping)
  ))
_sym_db.RegisterMessage(FbUserMapping)


# @@protoc_insertion_point(module_scope)
