# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Game.proto',
  package='PBData',
  serialized_pb=_b('\n\nGame.proto\x12\x06PBData\"M\n\x0cGameStartLog\x12\x0b\n\x03uid\x18\x01 \x02(\r\x12\x0e\n\x06gameid\x18\x02 \x02(\r\x12\r\n\x05\x63ount\x18\x03 \x01(\r\x12\x11\n\tlaststart\x18\x04 \x01(\r\"X\n\x0cGameLoginLog\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07game_id\x18\x02 \x01(\r\x12\x0b\n\x03uid\x18\x03 \x01(\x04\x12\n\n\x02ip\x18\x04 \x01(\r\x12\x12\n\nlogin_time\x18\x05 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GAMESTARTLOG = _descriptor.Descriptor(
  name='GameStartLog',
  full_name='PBData.GameStartLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='PBData.GameStartLog.uid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameid', full_name='PBData.GameStartLog.gameid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='PBData.GameStartLog.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laststart', full_name='PBData.GameStartLog.laststart', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=99,
)


_GAMELOGINLOG = _descriptor.Descriptor(
  name='GameLoginLog',
  full_name='PBData.GameLoginLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.GameLoginLog.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='PBData.GameLoginLog.game_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='PBData.GameLoginLog.uid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='PBData.GameLoginLog.ip', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='login_time', full_name='PBData.GameLoginLog.login_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['GameStartLog'] = _GAMESTARTLOG
DESCRIPTOR.message_types_by_name['GameLoginLog'] = _GAMELOGINLOG

GameStartLog = _reflection.GeneratedProtocolMessageType('GameStartLog', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTARTLOG,
  __module__ = 'Game_pb2'
  # @@protoc_insertion_point(class_scope:PBData.GameStartLog)
  ))
_sym_db.RegisterMessage(GameStartLog)

GameLoginLog = _reflection.GeneratedProtocolMessageType('GameLoginLog', (_message.Message,), dict(
  DESCRIPTOR = _GAMELOGINLOG,
  __module__ = 'Game_pb2'
  # @@protoc_insertion_point(class_scope:PBData.GameLoginLog)
  ))
_sym_db.RegisterMessage(GameLoginLog)


# @@protoc_insertion_point(module_scope)
