# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GdpProtocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GdpProtocol.proto',
  package='PBData.GDP',
  serialized_pb=_b('\n\x11GdpProtocol.proto\x12\nPBData.GDP\"w\n\x05Query\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06params\x18\x02 \x03(\x0c\x12\x0e\n\x06option\x18\x03 \x01(\r\"@\n\x06Option\x12\x18\n\x14OPTION_QUERY_FROM_DB\x10\x10\x12\x1c\n\x18OPTION_QUERY_FROM_MASTER\x10 \"9\n\x07Request\x12\n\n\x02id\x18\x01 \x02(\r\x12\"\n\x07queries\x18\x02 \x03(\x0b\x32\x11.PBData.GDP.Query\"\xd2\x02\n\x06Result\x12)\n\x06status\x18\x01 \x02(\x0e\x32\x19.PBData.GDP.Result.Status\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x0c\"\x8e\x02\n\x06Status\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x10\n\x0cSTATUS_ERROR\x10\x01\x12\x17\n\x13STATUS_ERROR_SERVER\x10\x02\x12\x15\n\x11STATUS_ERROR_AUTH\x10\x03\x12\x16\n\x12STATUS_ERROR_PARAM\x10\x04\x12\x17\n\x13STATUS_ERROR_CONFIG\x10\x05\x12\x18\n\x14STATUS_ERROR_STORAGE\x10\x06\x12\x15\n\x11STATUS_ERROR_DATA\x10\x07\x12\x18\n\x14STATUS_ERROR_NO_DATA\x10\x08\x12\x16\n\x12STATUS_ERROR_EXIST\x10\t\x12\x1a\n\x16STATUS_ERROR_NOT_EXIST\x10\n\"8\n\x05Reply\x12\n\n\x02id\x18\x01 \x02(\r\x12#\n\x07results\x18\x02 \x03(\x0b\x32\x12.PBData.GDP.Result')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_QUERY_OPTION = _descriptor.EnumDescriptor(
  name='Option',
  full_name='PBData.GDP.Query.Option',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPTION_QUERY_FROM_DB', index=0, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPTION_QUERY_FROM_MASTER', index=1, number=32,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=88,
  serialized_end=152,
)
_sym_db.RegisterEnumDescriptor(_QUERY_OPTION)

_RESULT_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='PBData.GDP.Result.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_SERVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_AUTH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_PARAM', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_CONFIG', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_STORAGE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_DATA', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_NO_DATA', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_EXIST', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ERROR_NOT_EXIST', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=282,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_RESULT_STATUS)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='PBData.GDP.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PBData.GDP.Query.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='PBData.GDP.Query.params', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='option', full_name='PBData.GDP.Query.option', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERY_OPTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=152,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='PBData.GDP.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.GDP.Request.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queries', full_name='PBData.GDP.Request.queries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=211,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='PBData.GDP.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='PBData.GDP.Result.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='PBData.GDP.Result.data', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESULT_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=552,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='PBData.GDP.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.GDP.Reply.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='results', full_name='PBData.GDP.Reply.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=610,
)

_QUERY_OPTION.containing_type = _QUERY
_REQUEST.fields_by_name['queries'].message_type = _QUERY
_RESULT.fields_by_name['status'].enum_type = _RESULT_STATUS
_RESULT_STATUS.containing_type = _RESULT
_REPLY.fields_by_name['results'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'GdpProtocol_pb2'
  # @@protoc_insertion_point(class_scope:PBData.GDP.Query)
  ))
_sym_db.RegisterMessage(Query)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'GdpProtocol_pb2'
  # @@protoc_insertion_point(class_scope:PBData.GDP.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'GdpProtocol_pb2'
  # @@protoc_insertion_point(class_scope:PBData.GDP.Result)
  ))
_sym_db.RegisterMessage(Result)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'GdpProtocol_pb2'
  # @@protoc_insertion_point(class_scope:PBData.GDP.Reply)
  ))
_sym_db.RegisterMessage(Reply)


# @@protoc_insertion_point(module_scope)
