# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IMMessage.proto',
  package='PBData.IM',
  serialized_pb=_b('\n\x0fIMMessage.proto\x12\tPBData.IM\"g\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03sid\x18\x02 \x01(\r\x12\x0b\n\x03\x64id\x18\x03 \x01(\x04\x12\x11\n\ttimestamp\x18\x04 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\x12\x12\n\nattachment\x18\x06 \x01(\x0c\"|\n\x0cNotification\x12\x0b\n\x03uid\x18\x01 \x02(\r\x12\x0b\n\x03nid\x18\x02 \x02(\r\x12\x12\n\ncreatetime\x18\x03 \x01(\r\x12\x0e\n\x06param1\x18\x04 \x01(\r\x12\x0e\n\x06param2\x18\x05 \x01(\r\x12\x0e\n\x06param3\x18\x06 \x01(\t\x12\x0e\n\x06param4\x18\x07 \x01(\t\"i\n\x0cNotifyConfig\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x0b\n\x03nid\x18\x02 \x02(\r\x12\x0e\n\x06param1\x18\x03 \x01(\r\x12\x0e\n\x06param2\x18\x04 \x01(\r\x12\x0e\n\x06param3\x18\x05 \x01(\t\x12\x0e\n\x06param4\x18\x06 \x01(\t\"\xd0\x01\n\x0fOfflineFileInfo\x12\x0e\n\x06\x66ileid\x18\x01 \x02(\x04\x12\x0f\n\x07\x66romuid\x18\x02 \x02(\x05\x12\r\n\x05touid\x18\x03 \x02(\x05\x12\x10\n\x08\x66ilesize\x18\x04 \x01(\x04\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\x12\x12\n\nprefixurls\x18\x06 \x01(\t\x12\x0e\n\x06numurl\x18\x07 \x01(\x05\x12\x13\n\x0bsegmentsize\x18\x08 \x01(\x05\x12\x12\n\ncreatetime\x18\t \x01(\r\x12\x0e\n\x06totype\x18\n \x01(\r\x12\x0c\n\x04toid\x18\x0b \x01(\x04\"R\n\x0eOfflineMessage\x12\x0b\n\x03uid\x18\x01 \x02(\r\x12\x10\n\x08\x66romtype\x18\x02 \x02(\r\x12\x0e\n\x06\x66romid\x18\x03 \x02(\x04\x12\x11\n\tmessageid\x18\x04 \x02(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='PBData.IM.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBData.IM.Message.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid', full_name='PBData.IM.Message.sid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='did', full_name='PBData.IM.Message.did', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PBData.IM.Message.timestamp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='PBData.IM.Message.content', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attachment', full_name='PBData.IM.Message.attachment', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=133,
)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='PBData.IM.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='PBData.IM.Notification.uid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nid', full_name='PBData.IM.Notification.nid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='PBData.IM.Notification.createtime', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param1', full_name='PBData.IM.Notification.param1', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param2', full_name='PBData.IM.Notification.param2', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param3', full_name='PBData.IM.Notification.param3', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param4', full_name='PBData.IM.Notification.param4', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=259,
)


_NOTIFYCONFIG = _descriptor.Descriptor(
  name='NotifyConfig',
  full_name='PBData.IM.NotifyConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PBData.IM.NotifyConfig.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nid', full_name='PBData.IM.NotifyConfig.nid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param1', full_name='PBData.IM.NotifyConfig.param1', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param2', full_name='PBData.IM.NotifyConfig.param2', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param3', full_name='PBData.IM.NotifyConfig.param3', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param4', full_name='PBData.IM.NotifyConfig.param4', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=366,
)


_OFFLINEFILEINFO = _descriptor.Descriptor(
  name='OfflineFileInfo',
  full_name='PBData.IM.OfflineFileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileid', full_name='PBData.IM.OfflineFileInfo.fileid', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fromuid', full_name='PBData.IM.OfflineFileInfo.fromuid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='touid', full_name='PBData.IM.OfflineFileInfo.touid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filesize', full_name='PBData.IM.OfflineFileInfo.filesize', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='PBData.IM.OfflineFileInfo.filename', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prefixurls', full_name='PBData.IM.OfflineFileInfo.prefixurls', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numurl', full_name='PBData.IM.OfflineFileInfo.numurl', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segmentsize', full_name='PBData.IM.OfflineFileInfo.segmentsize', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='PBData.IM.OfflineFileInfo.createtime', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totype', full_name='PBData.IM.OfflineFileInfo.totype', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toid', full_name='PBData.IM.OfflineFileInfo.toid', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=577,
)


_OFFLINEMESSAGE = _descriptor.Descriptor(
  name='OfflineMessage',
  full_name='PBData.IM.OfflineMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='PBData.IM.OfflineMessage.uid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fromtype', full_name='PBData.IM.OfflineMessage.fromtype', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fromid', full_name='PBData.IM.OfflineMessage.fromid', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageid', full_name='PBData.IM.OfflineMessage.messageid', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=661,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
DESCRIPTOR.message_types_by_name['NotifyConfig'] = _NOTIFYCONFIG
DESCRIPTOR.message_types_by_name['OfflineFileInfo'] = _OFFLINEFILEINFO
DESCRIPTOR.message_types_by_name['OfflineMessage'] = _OFFLINEMESSAGE

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'IMMessage_pb2'
  # @@protoc_insertion_point(class_scope:PBData.IM.Message)
  ))
_sym_db.RegisterMessage(Message)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATION,
  __module__ = 'IMMessage_pb2'
  # @@protoc_insertion_point(class_scope:PBData.IM.Notification)
  ))
_sym_db.RegisterMessage(Notification)

NotifyConfig = _reflection.GeneratedProtocolMessageType('NotifyConfig', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYCONFIG,
  __module__ = 'IMMessage_pb2'
  # @@protoc_insertion_point(class_scope:PBData.IM.NotifyConfig)
  ))
_sym_db.RegisterMessage(NotifyConfig)

OfflineFileInfo = _reflection.GeneratedProtocolMessageType('OfflineFileInfo', (_message.Message,), dict(
  DESCRIPTOR = _OFFLINEFILEINFO,
  __module__ = 'IMMessage_pb2'
  # @@protoc_insertion_point(class_scope:PBData.IM.OfflineFileInfo)
  ))
_sym_db.RegisterMessage(OfflineFileInfo)

OfflineMessage = _reflection.GeneratedProtocolMessageType('OfflineMessage', (_message.Message,), dict(
  DESCRIPTOR = _OFFLINEMESSAGE,
  __module__ = 'IMMessage_pb2'
  # @@protoc_insertion_point(class_scope:PBData.IM.OfflineMessage)
  ))
_sym_db.RegisterMessage(OfflineMessage)


# @@protoc_insertion_point(module_scope)
